name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_savannah
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_savannah
        REDIS_URL: redis://localhost:6379/1
        SECRET_KEY: test-secret-key
        DEBUG: True
        DJANGO_SETTINGS_MODULE: config.settings.development
      run: |
        python manage.py migrate --settings=config.settings.development
        pytest --cov=apps --cov-report=xml --cov-report=term-missing

  lint:
    runs-on: ubuntu-latest
    continue-on-error: true  
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy
        black --check . || true
        isort --check-only . || true
        flake8 --max-line-length=88 --extend-ignore=E203,W503 || true
        mypy . --ignore-missing-imports || true

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Bandit
      uses: tj-actions/bandit@v5.1
      with:
        targets: "apps config"
        options: "-r -f json -o bandit-report.json"

  build:
    needs: [test, security]  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        docker build -t savannah-ecommerce:${{ github.sha }} .
        docker run --rm savannah-ecommerce:${{ github.sha }} python manage.py check --settings=config.settings.production
